### ISSUE TITLE
Jewels: no. 29, subject title

### ISSUE THREAD

**Issue by melanieWacker** [melanieWacker/dlc-metadata-cleanup#25]
I don't believe the correct title has been pulled into the subject_title for 029_000 and 029. It appears the version on this printing block is only in Tibetan. "Polyglot" means it's in more than two languages. If there is no matching authority feel free to delete from this column and to record the information in a note.

**Comment by ErinPetrella** [comment]
From what I can tell, all three words in the title are Sanskrit, and together they form the normalized name for the sacred texts commonly referred to as the Prajnaparamita sutras in English. There doesn't appear to be a normalized Tibetan title. Since we don't know which of the sutras this is, we can certainly move it to a note field, but I do think that's the accepted title. Will look a bit further into it. To be clear, for subject_titles, do we want to stick to the original language represented in the object wherever possible?

**Comment by melanieWacker** [comment]
The problem is the addition of "Polyglot" which refers to a particular expression of the work. If there is an authority on the work level you could use that.

**Comment by ErinPetrella** [comment]
I see, I must have updated that after I sent you the rough draft. Yes, there is a work level authority for it. http://id.worldcat.org/fast/1356325
